import { Kanit } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/aurora-background";

const kanit = Kanit({
	variable: "--font-kanit",
	subsets: ["thai"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="th">
			<body className={`${kanit.variable} ${geistMono.variable} antialiased`}>
				<AuroraBackground>{children}</AuroraBackground>
			</body>
		</html>
	);
}
